---
- name: Filebeat and Metricbeat installation
  hosts: webservers
  become: true
  tasks:

  - name: Download filebeat deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

  - name: Depackage/Install filebeat file
    command: dpkg -i filebeat-7.4.0-amd64.deb

  - name: copy filebeat config files to container
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: enable filebeat
    command: filebeat modules enable system

  - name: setup filebeat
    command: filebeat setup

  - name: start filebeat
    command: service filebeat start

  - name: enable filebeat on reboot
    systemd:
      name: filebeat
      state: started
      enabled: yes

  - name: Download metricbeat deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: Depackage/Install metricbeat file
    command: dpkg -i metricbeat-7.4.0-amd64.deb

  - name: copy metricbeat config files to container
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable metricbeat
    command: metricbeat modules enable docker

  - name: setup metricbeat
    command: metricbeat setup

  - name: start metricbeat
    command: service metricbeat start

  - name: enable metricbeat on reboot
    systemd:
      name: metricbeat
      state: started
      enabled: yes
