---
- name: Config Web VM with Docker
  hosts: webservers
  become: true
  tasks:

  - name: Install docker.io (apt, state=present is optional)
    apt:
#      update_cache: yes
      name: docker.io
      state: present

  - name: Install python3-pip (apt, state=present is optional)
    apt:
      name: python3-pip
      state: present

  - name: Install python docker module (pip, state=present is optional)
    pip:
      name: docker
      state: present

  - name: Install cyberxsecurity/dvwa container (docker-container, state=present is optional)
    community.docker.docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      state: started
      restart_policy: always
      published_ports: 80:80

  - name: Start docker service
    systemd:
      name: docker
      enabled: yes
